/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Agent = string
export type Plandescription = string
export type Taskid = string
export type Taskid1 = string
export type Limit = number
export type Status = (string | null)
export type Taskid2 = string
export type Scheduleddate = string
export type Taskid3 = string
export type Scheduleddate1 = string
export type Taskid4 = string
export type Conversationid = (string | null)
export type Title = string
export type Relatedactivityids = (string[] | null)
export type Metadata = ({
[k: string]: unknown
} | null)
export type Modelid = (string | null)
export type Activityids = string[]
export type Conversationid1 = string
export type Content = string
export type Images = (string[] | null)
export type Modelid1 = (string | null)
export type Limit1 = (number | null)
export type Offset = (number | null)
export type Conversationid2 = string
export type Limit2 = (number | null)
export type Offset1 = (number | null)
export type Conversationid3 = string
export type Conversationids = (string[] | null)
export type Conversationid4 = string
export type Modelid2 = string
export type Model = string
export type Prompttokens = number
export type Completiontokens = number
export type Totaltokens = number
export type Cost = number
export type Requesttype = string
export type Dimension = string
export type Days = number
export type Startdate = (string | null)
export type Enddate = (string | null)
export type Modelconfigid = (string | null)
export type Enabled = (boolean | null)
export type Interval = (number | null)
export type Datawindow = (number | null)
export type Enablesystemnotification = (boolean | null)
export type Enablelive2Ddisplay = (boolean | null)
export type Limit3 = number
export type Offset2 = number
export type Name = string
export type RootModelStr = string
export type Hashes = string[]
export type Maxagehours = number
export type Enabled1 = (boolean | null)
export type Strategy = (string | null)
export type Phashthreshold = (number | null)
export type Mininterval = (number | null)
export type Maximages = (number | null)
export type Enablecontentanalysis = (boolean | null)
export type Enabletextdetection = (boolean | null)
export type Filepath = string
export type Limit4 = number
export type Offset3 = number
export type Id = string
export type Includecompleted = boolean
export type Todoid = string
export type Scheduleddate2 = string
export type Scheduledtime = (string | null)
export type Todoid1 = string
export type Date = string
export type Limit5 = number
export type Enabled2 = (boolean | null)
export type Selectedmodelurl = (string | null)
export type Modeldir = (string | null)
export type Remotemodels = (string[] | null)
export type Notificationduration = (number | null)
export type Name1 = string
/**
 * Provider identifier
 */
export type Provider = (string | null)
export type Apiurl = string
export type Model1 = string
export type Inputtokenprice = number
export type Outputtokenprice = number
export type Currency = string
export type Apikey = string
export type Modelid3 = string
export type Name2 = (string | null)
export type Apiurl1 = (string | null)
export type Model2 = (string | null)
export type Inputtokenprice1 = (number | null)
export type Outputtokenprice1 = (number | null)
/**
 * Provider identifier
 */
export type Provider1 = (string | null)
export type Currency1 = (string | null)
export type Apikey1 = (string | null)
export type Modelid4 = string
export type Modelid5 = string
export type Modelid6 = string
export type Limit6 = number
export type Eventtype = (string | null)
export type Starttime = (string | null)
export type Endtime = (string | null)
export type RootModelNoneType = null
/**
 * Permission type enumeration
 */
export type PermissionType = ("accessibility" | "screen_recording")
export type Delayseconds = number
export type Limit7 = number
export type Eventtype1 = (string | null)
export type Starttime1 = (string | null)
export type Endtime1 = (string | null)
export type Limit8 = number
export type Offset4 = number
export type Eventid = string
export type Activityid = string
export type Activityid1 = string
export type Eventid1 = string
export type Days1 = number
export type Version = number
export type Limit9 = number
export type Startdate1 = string
export type Enddate1 = string
export type Startdate2 = string
export type Enddate2 = string
export type Startdate3 = string
export type Enddate3 = string
export type Startdate4 = string
export type Enddate4 = string
export type Databasepath = (string | null)
export type Screenshotsavepath = (string | null)
export type Compressionlevel = (string | null)
export type Enableregioncropping = (boolean | null)
export type Cropthreshold = (number | null)
export type Show = string
export type Hide = string
export type Dashboard = string
export type Activity = string
export type Chat = string
export type Agents = string
export type Settings = string
export type About = string
export type Quit = string
export type Success = boolean
export type Message = string
export type Visible = boolean
export type Success1 = boolean
export type Visible1 = boolean

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
create_task: {
input: CreateTaskRequest
output: RootModelDictStrAny
}
execute_task: {
input: ExecuteTaskRequest
output: RootModelDictStrAny
}
delete_task: {
input: DeleteTaskRequest
output: RootModelDictStrAny
}
get_tasks: {
input: GetTasksRequest
output: RootModelDictStrAny
}
get_available_agents: {
input: GetAvailableAgentsRequest
output: RootModelDictStrAny
}
get_task_status: {
input: ExecuteTaskRequest
output: RootModelDictStrAny
}
schedule_task: {
input: ScheduleTaskRequest
output: RootModelDictStrAny
}
unschedule_task: {
input: UnscheduleTaskRequest
output: RootModelDictStrAny
}
get_tasks_by_date: {
input: GetTasksByDateRequest
output: RootModelDictStrAny
}
execute_task_in_chat: {
input: ExecuteTaskInChatRequest
output: RootModelDictStrAny
}
create_conversation: {
input: CreateConversationRequest
output: RootModelDictStrAny
}
create_conversation_from_activities: {
input: CreateConversationFromActivitiesRequest
output: RootModelDictStrAny
}
send_message: {
input: SendMessageRequest
output: RootModelDictStrAny
}
get_conversations: {
input: GetConversationsRequest
output: RootModelDictStrAny
}
get_messages: {
input: GetMessagesRequest
output: RootModelDictStrAny
}
delete_conversation: {
input: DeleteConversationRequest
output: RootModelDictStrAny
}
get_streaming_status: {
input: GetStreamingStatusRequest
output: RootModelDictStrAny
}
cancel_stream: {
input: CancelStreamRequest
output: RootModelDictStrAny
}
get_llm_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_llm_stats_by_model: {
input: GetLLMStatsByModelRequest
output: RootModelDictStrAny
}
record_llm_usage: {
input: RecordLLMUsageRequest
output: RootModelDictStrAny
}
get_usage_summary: {
input: void | undefined
output: RootModelDictStrAny
}
get_daily_llm_usage: {
input: void | undefined
output: RootModelDictStrAny
}
get_model_distribution: {
input: void | undefined
output: RootModelDictStrAny
}
get_llm_usage_trend: {
input: GetLLMUsageTrendRequest
output: RootModelDictStrAny
}
get_friendly_chat_settings: {
input: void | undefined
output: RootModelDictStrAny
}
update_friendly_chat_settings: {
input: UpdateFriendlyChatSettingsRequest
output: RootModelDictStrAny
}
get_friendly_chat_history: {
input: GetFriendlyChatHistoryRequest
output: RootModelDictStrAny
}
trigger_friendly_chat: {
input: void | undefined
output: RootModelDictStrAny
}
greeting: {
input: Person
output: RootModelStr
}
get_image_stats: {
input: void | undefined
output: RootModelDict
}
get_cached_images: {
input: GetImagesRequest
output: RootModelDict
}
cleanup_old_images: {
input: CleanupImagesRequest
output: RootModelDict
}
clear_memory_cache: {
input: void | undefined
output: RootModelDict
}
get_image_optimization_config: {
input: void | undefined
output: RootModelDictStrAny
}
get_image_optimization_stats: {
input: void | undefined
output: RootModelDict
}
update_image_optimization_config: {
input: ImageOptimizationConfigRequest
output: RootModelDictStrAny
}
read_image_file: {
input: ReadImageFileRequest
output: RootModelDict
}
get_recent_events: {
input: GetRecentEventsRequest
output: RootModelDictStrAny
}
get_knowledge_list: {
input: void | undefined
output: RootModelDictStrAny
}
delete_knowledge: {
input: DeleteItemRequest
output: RootModelDictStrAny
}
get_todo_list: {
input: GetTodoListRequest
output: RootModelDictStrAny
}
delete_todo: {
input: DeleteItemRequest
output: RootModelDictStrAny
}
schedule_todo: {
input: ScheduleTodoRequest
output: RootModelDictStrAny
}
unschedule_todo: {
input: UnscheduleTodoRequest
output: RootModelDictStrAny
}
generate_diary: {
input: GenerateDiaryRequest
output: RootModelDictStrAny
}
get_diary_list: {
input: GetDiaryListRequest
output: RootModelDictStrAny
}
delete_diary: {
input: DeleteItemRequest
output: RootModelDictStrAny
}
get_pipeline_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_event_count_by_date: {
input: void | undefined
output: RootModelDictStrAny
}
get_knowledge_count_by_date: {
input: void | undefined
output: RootModelDictStrAny
}
get_live2d_settings: {
input: void | undefined
output: RootModelDictStrAny
}
update_live2d_settings: {
input: UpdateLive2DSettingsRequest
output: RootModelDictStrAny
}
create_model: {
input: CreateModelRequest
output: RootModelDictStrAny
}
update_model: {
input: UpdateModelRequest
output: RootModelDictStrAny
}
delete_model: {
input: DeleteModelRequest
output: RootModelDictStrAny
}
list_models: {
input: void | undefined
output: RootModelDictStrAny
}
get_active_model: {
input: void | undefined
output: RootModelDictStrAny
}
select_model: {
input: SelectModelRequest
output: RootModelDictStrAny
}
test_model: {
input: TestModelRequest
output: RootModelDictStrAny
}
migrate_models_to_openai: {
input: void | undefined
output: RootModelDictStrAny
}
get_perception_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_records: {
input: GetRecordsRequest
output: RootModelDictStrAny
}
start_perception: {
input: void | undefined
output: RootModelDictStrAny
}
stop_perception: {
input: void | undefined
output: RootModelDictStrAny
}
clear_records: {
input: void | undefined
output: RootModelDictStrAny
}
get_buffered_events: {
input: void | undefined
output: RootModelDictStrAny
}
check_permissions: {
input: RootModelNoneType
output: RootModelDict
}
open_system_settings: {
input: OpenSystemSettingsRequest
output: RootModelDict
}
request_accessibility_permission: {
input: RootModelNoneType
output: RootModelDict
}
restart_app: {
input: RestartAppRequest
output: RootModelDict
}
get_processing_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_events: {
input: GetEventsRequest
output: RootModelDictStrAny
}
get_activities: {
input: GetActivitiesRequest
output: RootModelDictStrAny
}
get_event_by_id: {
input: GetEventByIdRequest
output: RootModelDictStrAny
}
get_activity_by_id: {
input: GetActivityByIdRequest
output: RootModelDictStrAny
}
delete_activity: {
input: DeleteActivityRequest
output: RootModelDictStrAny
}
delete_event: {
input: DeleteEventRequest
output: RootModelDictStrAny
}
start_processing: {
input: void | undefined
output: RootModelDictStrAny
}
stop_processing: {
input: void | undefined
output: RootModelDictStrAny
}
finalize_current_activity: {
input: void | undefined
output: RootModelDictStrAny
}
cleanup_old_data: {
input: CleanupOldDataRequest
output: RootModelDictStrAny
}
get_persistence_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_activities_incremental: {
input: GetActivitiesIncrementalRequest
output: RootModelDictStrAny
}
get_activity_count_by_date: {
input: GetActivityCountByDateRequest
output: RootModelDictStrAny
}
delete_activities_by_date: {
input: DeleteActivitiesByDateRequest
output: RootModelDictStrAny
}
delete_knowledge_by_date: {
input: DeleteKnowledgeByDateRequest
output: RootModelDictStrAny
}
delete_todos_by_date: {
input: DeleteTodosByDateRequest
output: RootModelDictStrAny
}
delete_diaries_by_date: {
input: DeleteDiariesByDateRequest
output: RootModelDictStrAny
}
get_monitors: {
input: void | undefined
output: RootModelDictStrAny
}
start_monitors_auto_refresh: {
input: RootModelDictStrAny
output: RootModelDictStrAny
}
stop_monitors_auto_refresh: {
input: void | undefined
output: RootModelDictStrAny
}
get_monitors_auto_refresh_status: {
input: void | undefined
output: RootModelDictStrAny
}
get_screen_settings: {
input: void | undefined
output: RootModelDictStrAny
}
capture_all_previews: {
input: void | undefined
output: RootModelDictStrAny
}
update_screen_settings: {
input: RootModelDictStrAny
output: RootModelDictStrAny
}
get_perception_settings: {
input: void | undefined
output: RootModelDictStrAny
}
update_perception_settings: {
input: RootModelDictStrAny
output: RootModelDictStrAny
}
check_initial_setup: {
input: void | undefined
output: RootModelDictStrAny
}
start_system: {
input: void | undefined
output: RootModelDictStrAny
}
stop_system: {
input: void | undefined
output: RootModelDictStrAny
}
get_system_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_database_path: {
input: void | undefined
output: RootModelDictStrAny
}
get_settings_info: {
input: void | undefined
output: RootModelDictStrAny
}
update_settings: {
input: UpdateSettingsRequest
output: RootModelDictStrAny
}
get_image_compression_config: {
input: void | undefined
output: RootModelDictStrAny
}
update_image_compression_config: {
input: ImageCompressionConfigRequest
output: RootModelDictStrAny
}
get_image_compression_stats: {
input: void | undefined
output: RootModelDictStrAny
}
reset_image_compression_stats: {
input: void | undefined
output: RootModelDictStrAny
}
update_tray_menu: {
input: TrayUpdateRequest
output: TrayUpdateResponse
}
set_tray_visibility: {
input: TrayVisibilityRequest
output: TrayVisibilityResponse
}
}
/**
 * Request parameters for creating a new agent task.
 * 
 * @property agent - The agent type to use.
 * @property planDescription - The task description/plan.
 */
export interface CreateTaskRequest {
agent: Agent
planDescription: Plandescription
}
export interface RootModelDictStrAny {
[k: string]: unknown
}
/**
 * Request parameters for executing a task.
 * 
 * @property taskId - The task ID to execute.
 */
export interface ExecuteTaskRequest {
taskId: Taskid
}
/**
 * Request parameters for deleting a task.
 * 
 * @property taskId - The task ID to delete.
 */
export interface DeleteTaskRequest {
taskId: Taskid1
}
/**
 * Request parameters for getting tasks.
 * 
 * @property limit - Maximum number of tasks to return (1-100).
 * @property status - Optional status filter.
 */
export interface GetTasksRequest {
limit?: Limit
status?: Status
}
/**
 * Request parameters for getting available agents.
 * 
 * No parameters needed.
 */
export interface GetAvailableAgentsRequest {

}
/**
 * Request parameters for scheduling a task to a specific date.
 * 
 * @property taskId - The task ID to schedule.
 * @property scheduledDate - The date to schedule the task (YYYY-MM-DD format).
 */
export interface ScheduleTaskRequest {
taskId: Taskid2
scheduledDate: Scheduleddate
}
/**
 * Request parameters for moving a task back to pending.
 * 
 * @property taskId - The task ID to unschedule.
 */
export interface UnscheduleTaskRequest {
taskId: Taskid3
}
/**
 * Request parameters for getting tasks scheduled for a specific date.
 * 
 * @property scheduledDate - The date to query tasks (YYYY-MM-DD format).
 */
export interface GetTasksByDateRequest {
scheduledDate: Scheduleddate1
}
/**
 * Request parameters for executing a task in chat.
 * 
 * @property taskId - The task ID to execute.
 * @property conversationId - Optional conversation ID, creates new if not provided.
 */
export interface ExecuteTaskInChatRequest {
taskId: Taskid4
conversationId?: Conversationid
}
/**
 * Create conversation request
 */
export interface CreateConversationRequest {
title: Title
relatedActivityIds?: Relatedactivityids
metadata?: Metadata
modelId?: Modelid
}
/**
 * Create conversation from activities request
 */
export interface CreateConversationFromActivitiesRequest {
activityIds: Activityids
}
/**
 * Send message request
 */
export interface SendMessageRequest {
conversationId: Conversationid1
content: Content
images?: Images
modelId?: Modelid1
}
/**
 * Get conversation list request
 */
export interface GetConversationsRequest {
limit?: Limit1
offset?: Offset
}
/**
 * Get message list request
 */
export interface GetMessagesRequest {
conversationId: Conversationid2
limit?: Limit2
offset?: Offset1
}
/**
 * Delete conversation request
 */
export interface DeleteConversationRequest {
conversationId: Conversationid3
}
/**
 * Get streaming status request
 */
export interface GetStreamingStatusRequest {
conversationIds?: Conversationids
}
/**
 * Cancel streaming request
 */
export interface CancelStreamRequest {
conversationId: Conversationid4
}
/**
 * Request parameters for retrieving LLM statistics of a specific model.
 * 
 * @property modelId - The model configuration ID.
 */
export interface GetLLMStatsByModelRequest {
modelId: Modelid2
}
/**
 * Request parameters for recording LLM usage statistics.
 * 
 * @property model - The LLM model name used.
 * @property promptTokens - Number of prompt tokens consumed.
 * @property completionTokens - Number of completion tokens consumed.
 * @property totalTokens - Total number of tokens consumed.
 * @property cost - Cost of the request (optional).
 * @property requestType - Type of request (e.g., 'summarization', 'agent', 'chat').
 */
export interface RecordLLMUsageRequest {
model: Model
promptTokens?: Prompttokens
completionTokens?: Completiontokens
totalTokens?: Totaltokens
cost?: Cost
requestType: Requesttype
}
/**
 * Request parameters for retrieving LLM usage trend data.
 * 
 * @property dimension - Time dimension for aggregation ('day', 'week', 'month', 'custom').
 * @property days - Number of days to query when no explicit range provided (1-365).
 * @property startDate - Optional ISO datetime string marking the beginning of the range.
 * @property endDate - Optional ISO datetime string marking the end of the range.
 * @property modelConfigId - Optional model configuration ID filter.
 */
export interface GetLLMUsageTrendRequest {
dimension?: Dimension
days?: Days
startDate?: Startdate
endDate?: Enddate
modelConfigId?: Modelconfigid
}
/**
 * Request parameters for updating friendly chat settings.
 * 
 * @property enabled - Whether friendly chat feature is enabled.
 * @property interval - Interval in minutes for generating chat messages (1-120).
 * @property dataWindow - Time window in minutes for analyzing recent activities (5-120).
 * @property enableSystemNotification - Whether to show system notifications.
 * @property enableLive2dDisplay - Whether to display in Live2D character.
 */
export interface UpdateFriendlyChatSettingsRequest {
enabled?: Enabled
interval?: Interval
dataWindow?: Datawindow
enableSystemNotification?: Enablesystemnotification
enableLive2DDisplay?: Enablelive2Ddisplay
}
/**
 * Request parameters for getting friendly chat history.
 * 
 * @property limit - Maximum number of chat messages to return (1-100).
 * @property offset - Number of messages to skip (>=0).
 */
export interface GetFriendlyChatHistoryRequest {
limit?: Limit3
offset?: Offset2
}
/**
 * A simple model representing a person.
 * 
 * @property name - The name of the person.
 */
export interface Person {
name: Name
}
export interface RootModelDict {
[k: string]: unknown
}
/**
 * Get images request model
 */
export interface GetImagesRequest {
hashes: Hashes
}
/**
 * Clean up images request model
 */
export interface CleanupImagesRequest {
maxAgeHours?: Maxagehours
}
/**
 * Request parameters for updating image optimization configuration.
 * 
 * @property enabled - Whether image optimization is enabled.
 * @property strategy - Optimization strategy ('phash', 'sampling', 'hybrid').
 * @property phashThreshold - Perceptual hash similarity threshold (0.0-1.0).
 * @property minInterval - Minimum time interval between images (seconds).
 * @property maxImages - Maximum number of images per event.
 * @property enableContentAnalysis - Enable content-based importance analysis.
 * @property enableTextDetection - Enable text detection for OCR-capable images.
 */
export interface ImageOptimizationConfigRequest {
enabled?: Enabled1
strategy?: Strategy
phashThreshold?: Phashthreshold
minInterval?: Mininterval
maxImages?: Maximages
enableContentAnalysis?: Enablecontentanalysis
enableTextDetection?: Enabletextdetection
}
/**
 * Request to read image file and return base64
 */
export interface ReadImageFileRequest {
filePath: Filepath
}
/**
 * Request parameters for getting recent events.
 * 
 * @property limit - Maximum number of events to return (1-200).
 * @property offset - Number of events to skip (>=0).
 */
export interface GetRecentEventsRequest {
limit?: Limit4
offset?: Offset3
}
/**
 * Request parameters for deleting an item (knowledge/todo/diary).
 * 
 * @property id - The item ID to delete.
 */
export interface DeleteItemRequest {
id: Id
}
/**
 * Request parameters for getting todo list.
 * 
 * @property includeCompleted - Whether to include completed todos.
 */
export interface GetTodoListRequest {
includeCompleted?: Includecompleted
}
/**
 * Request parameters for scheduling a todo to a specific date.
 * 
 * @property todoId - The todo ID to schedule.
 * @property scheduledDate - The date to schedule the todo (YYYY-MM-DD format).
 * @property scheduledTime - Optional time to schedule the todo (HH:MM format).
 */
export interface ScheduleTodoRequest {
todoId: Todoid
scheduledDate: Scheduleddate2
scheduledTime?: Scheduledtime
}
/**
 * Request parameters for unscheduling a todo.
 * 
 * @property todoId - The todo ID to unschedule.
 */
export interface UnscheduleTodoRequest {
todoId: Todoid1
}
/**
 * Request parameters for generating a diary.
 * 
 * @property date - The date for the diary (YYYY-MM-DD format).
 */
export interface GenerateDiaryRequest {
date: Date
}
/**
 * Request parameters for getting diary list.
 * 
 * @property limit - Maximum number of diaries to return (1-100).
 */
export interface GetDiaryListRequest {
limit?: Limit5
}
/**
 * Request parameters for updating Live2D configuration.
 * 
 * @property enabled - Whether the Live2D companion window should be shown.
 * @property selectedModelUrl - Currently selected Live2D model URL.
 * @property modelDir - Optional local model directory path.
 * @property remoteModels - Remote model URLs saved in configuration.
 * @property notificationDuration - Duration in milliseconds for notification display (1000-30000).
 */
export interface UpdateLive2DSettingsRequest {
enabled?: Enabled2
selectedModelUrl?: Selectedmodelurl
modelDir?: Modeldir
remoteModels?: Remotemodels
notificationDuration?: Notificationduration
}
/**
 * Request parameters for creating a new model configuration.
 * 
 * @property name - Display name for the model.
 * @property apiUrl - API endpoint base URL.
 * @property model - Model identifier/name.
 * @property inputTokenPrice - Price per million input tokens.
 * @property outputTokenPrice - Price per million output tokens.
 * @property currency - Currency code (optional, defaults to 'USD').
 * @property apiKey - API authentication key.
 * 
 * Note: Provider is automatically set to 'openai' for OpenAI-compatible APIs.
 */
export interface CreateModelRequest {
name: Name1
provider?: Provider
apiUrl: Apiurl
model: Model1
inputTokenPrice: Inputtokenprice
outputTokenPrice: Outputtokenprice
currency?: Currency
apiKey: Apikey
}
/**
 * Request parameters for updating a model configuration.
 * 
 * @property modelId - The ID of the model to update.
 * @property name - Display name for the model (optional).
 * @property apiUrl - API endpoint base URL (optional).
 * @property model - Model identifier/name (optional).
 * @property inputTokenPrice - Price per million input tokens (optional).
 * @property outputTokenPrice - Price per million output tokens (optional).
 * @property currency - Currency code (optional).
 * @property apiKey - API authentication key (optional, leave empty to keep existing).
 * 
 * Note: Provider field is removed - all models use OpenAI-compatible format.
 */
export interface UpdateModelRequest {
modelId: Modelid3
name?: Name2
apiUrl?: Apiurl1
model?: Model2
inputTokenPrice?: Inputtokenprice1
outputTokenPrice?: Outputtokenprice1
provider?: Provider1
currency?: Currency1
apiKey?: Apikey1
}
/**
 * Request parameters for deleting a model configuration.
 * 
 * @property modelId - The ID of the model to delete.
 */
export interface DeleteModelRequest {
modelId: Modelid4
}
/**
 * Request parameters for selecting/switching to a model.
 * 
 * @property modelId - The ID of the model to activate.
 */
export interface SelectModelRequest {
modelId: Modelid5
}
/**
 * Request parameters for testing model connectivity.
 * 
 * @property modelId - The ID of the model to test.
 */
export interface TestModelRequest {
modelId: Modelid6
}
/**
 * Request parameters for getting records.
 * 
 * @property limit - Maximum number of records to return (1-1000).
 * @property eventType - Optional event type filter.
 * @property startTime - Optional start time filter (ISO format).
 * @property endTime - Optional end time filter (ISO format).
 */
export interface GetRecordsRequest {
limit?: Limit6
eventType?: Eventtype
startTime?: Starttime
endTime?: Endtime
}
/**
 * Open system settings request
 */
export interface OpenSystemSettingsRequest {
permissionType: PermissionType
}
/**
 * Restart app request
 */
export interface RestartAppRequest {
delaySeconds?: Delayseconds
}
/**
 * Request parameters for getting events.
 * 
 * @property limit - Maximum number of events to return (1-500).
 * @property eventType - Optional event type filter.
 * @property startTime - Optional start time filter (ISO format).
 * @property endTime - Optional end time filter (ISO format).
 */
export interface GetEventsRequest {
limit?: Limit7
eventType?: Eventtype1
startTime?: Starttime1
endTime?: Endtime1
}
/**
 * Request parameters for getting activities.
 * 
 * @property limit - Maximum number of activities to return (1-100).
 * @property offset - Number of activities to skip (>=0).
 */
export interface GetActivitiesRequest {
limit?: Limit8
offset?: Offset4
}
/**
 * Request parameters for getting event by ID.
 * 
 * @property eventId - The event ID.
 */
export interface GetEventByIdRequest {
eventId: Eventid
}
/**
 * Request parameters for getting activity by ID.
 * 
 * @property activityId - The activity ID.
 */
export interface GetActivityByIdRequest {
activityId: Activityid
}
/**
 * Request parameters for deleting an activity.
 * 
 * @property activityId - The activity ID to delete.
 */
export interface DeleteActivityRequest {
activityId: Activityid1
}
/**
 * Request parameters for deleting an event.
 * 
 * @property eventId - The event ID to delete.
 */
export interface DeleteEventRequest {
eventId: Eventid1
}
/**
 * Request parameters for cleaning up old data.
 * 
 * @property days - Number of days to keep (1-365).
 */
export interface CleanupOldDataRequest {
days?: Days1
}
/**
 * Request parameters for incremental activity updates.
 * 
 * @property version - The current version number from client (starts at 0).
 * @property limit - Maximum number of new activities to return (1-100).
 */
export interface GetActivitiesIncrementalRequest {
version?: Version
limit?: Limit9
}
/**
 * Request parameters for getting activity count by date.
 * 
 * Returns the total activity count for each date (no pagination, gets total count for all dates).
 */
export interface GetActivityCountByDateRequest {

}
/**
 * Request parameters for deleting activities in a date range.
 * 
 * @property startDate - Start date in YYYY-MM-DD format.
 * @property endDate - End date in YYYY-MM-DD format.
 */
export interface DeleteActivitiesByDateRequest {
startDate: Startdate1
endDate: Enddate1
}
/**
 * Request parameters for deleting knowledge in a date range.
 * 
 * @property startDate - Start date in YYYY-MM-DD format.
 * @property endDate - End date in YYYY-MM-DD format.
 */
export interface DeleteKnowledgeByDateRequest {
startDate: Startdate2
endDate: Enddate2
}
/**
 * Request parameters for deleting todos in a date range.
 * 
 * @property startDate - Start date in YYYY-MM-DD format.
 * @property endDate - End date in YYYY-MM-DD format.
 */
export interface DeleteTodosByDateRequest {
startDate: Startdate3
endDate: Enddate3
}
/**
 * Request parameters for deleting diaries in a date range.
 * 
 * @property startDate - Start date in YYYY-MM-DD format.
 * @property endDate - End date in YYYY-MM-DD format.
 */
export interface DeleteDiariesByDateRequest {
startDate: Startdate4
endDate: Enddate4
}
/**
 * Request parameters for updating application settings.
 * 
 * Note: LLM configuration has been migrated to multi-model management system
 * See CreateModelRequest and SelectModelRequest
 * 
 * @property databasePath - Path to the database file (optional).
 * @property screenshotSavePath - Path to save screenshots (optional).
 */
export interface UpdateSettingsRequest {
databasePath?: Databasepath
screenshotSavePath?: Screenshotsavepath
}
/**
 * Request parameters for updating image compression configuration.
 * 
 * @property compressionLevel - Compression level ('ultra', 'aggressive', 'balanced', 'quality').
 * @property enableRegionCropping - Whether to enable region-based cropping.
 * @property cropThreshold - Crop threshold percentage (0-100).
 */
export interface ImageCompressionConfigRequest {
compressionLevel?: Compressionlevel
enableRegionCropping?: Enableregioncropping
cropThreshold?: Cropthreshold
}
/**
 * Request to update tray menu labels with i18n translations.
 */
export interface TrayUpdateRequest {
show: Show
hide: Hide
dashboard: Dashboard
activity: Activity
chat: Chat
agents: Agents
settings: Settings
about: About
quit: Quit
}
/**
 * Response from tray update operation.
 */
export interface TrayUpdateResponse {
success: Success
message: Message
}
/**
 * Request to change tray icon visibility.
 */
export interface TrayVisibilityRequest {
visible: Visible
}
/**
 * Response from tray visibility operation.
 */
export interface TrayVisibilityResponse {
success: Success1
visible: Visible1
}
