/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Name = string
export type RootModelStr = string
export type Limit = number
export type Eventtype = (string | null)
export type Starttime = (string | null)
export type Endtime = (string | null)
export type Limit1 = number
export type Eventtype1 = (string | null)
export type Starttime1 = (string | null)
export type Endtime1 = (string | null)
export type Limit2 = number
export type Eventid = string
export type Activityid = string
export type Activityid1 = string
export type Days = number
export type Version = number
export type Limit3 = number
export type Databasepath = (string | null)
export type Screenshotsavepath = (string | null)
export type Enabled = boolean
export type Strategy = string
export type Phashthreshold = number
export type Mininterval = number
export type Maximages = number
export type Enablecontentanalysis = boolean
export type Enabletextdetection = boolean
export type Compressionlevel = (string | null)
export type Enableregioncropping = (boolean | null)
export type Cropthreshold = (number | null)
export type Agent = string
export type Plandescription = string
export type Taskid = string
export type Taskid1 = string
export type Limit4 = number
export type Status = (string | null)
export type Hashes = string[]
export type Maxagehours = number
export type Title = string
export type Relatedactivityids = (string[] | null)
export type Metadata = ({
[k: string]: unknown
} | null)
export type Activityids = string[]
export type Conversationid = string
export type Content = string
export type Limit5 = (number | null)
export type Offset = (number | null)
export type Conversationid1 = string
export type Limit6 = (number | null)
export type Offset1 = (number | null)
export type Conversationid2 = string
export type Modelid = string
export type Model = string
export type Prompttokens = number
export type Completiontokens = number
export type Totaltokens = number
export type Cost = number
export type Requesttype = string
export type Name1 = string
export type Provider = string
export type Apiurl = string
export type Model1 = string
export type Inputtokenprice = number
export type Outputtokenprice = number
export type Currency = string
export type Apikey = string
export type Modelid1 = string
export type Name2 = (string | null)
export type Provider1 = (string | null)
export type Apiurl1 = (string | null)
export type Model2 = (string | null)
export type Inputtokenprice1 = (number | null)
export type Outputtokenprice1 = (number | null)
export type Currency1 = (string | null)
export type Apikey1 = (string | null)
export type Modelid2 = string
export type Modelid3 = string
export type Modelid4 = string
export type Limit7 = number
export type Id = string
export type Includecompleted = boolean
export type Date = string

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
greeting: {
input: Person
output: RootModelStr
}
get_perception_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_records: {
input: GetRecordsRequest
output: RootModelDictStrAny
}
start_perception: {
input: void | undefined
output: RootModelDictStrAny
}
stop_perception: {
input: void | undefined
output: RootModelDictStrAny
}
clear_records: {
input: void | undefined
output: RootModelDictStrAny
}
get_buffered_events: {
input: void | undefined
output: RootModelDictStrAny
}
get_processing_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_events: {
input: GetEventsRequest
output: RootModelDictStrAny
}
get_activities: {
input: GetActivitiesRequest
output: RootModelDictStrAny
}
get_event_by_id: {
input: GetEventByIdRequest
output: RootModelDictStrAny
}
get_activity_by_id: {
input: GetActivityByIdRequest
output: RootModelDictStrAny
}
delete_activity: {
input: DeleteActivityRequest
output: RootModelDictStrAny
}
start_processing: {
input: void | undefined
output: RootModelDictStrAny
}
stop_processing: {
input: void | undefined
output: RootModelDictStrAny
}
finalize_current_activity: {
input: void | undefined
output: RootModelDictStrAny
}
cleanup_old_data: {
input: CleanupOldDataRequest
output: RootModelDictStrAny
}
get_persistence_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_activities_incremental: {
input: GetActivitiesIncrementalRequest
output: RootModelDictStrAny
}
get_activity_count_by_date: {
input: GetActivityCountByDateRequest
output: RootModelDictStrAny
}
start_system: {
input: void | undefined
output: RootModelDictStrAny
}
stop_system: {
input: void | undefined
output: RootModelDictStrAny
}
get_system_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_database_path: {
input: void | undefined
output: RootModelDictStrAny
}
get_settings_info: {
input: void | undefined
output: RootModelDictStrAny
}
update_settings: {
input: UpdateSettingsRequest
output: RootModelDictStrAny
}
get_image_optimization_config: {
input: void | undefined
output: RootModelDict
}
update_image_optimization_config: {
input: ImageOptimizationConfigRequest
output: RootModelDict
}
get_image_compression_config: {
input: void | undefined
output: RootModelDictStrAny
}
update_image_compression_config: {
input: ImageCompressionConfigRequest
output: RootModelDictStrAny
}
get_image_compression_stats: {
input: void | undefined
output: RootModelDictStrAny
}
reset_image_compression_stats: {
input: void | undefined
output: RootModelDictStrAny
}
create_task: {
input: CreateTaskRequest
output: RootModelDictStrAny
}
execute_task: {
input: ExecuteTaskRequest
output: RootModelDictStrAny
}
delete_task: {
input: DeleteTaskRequest
output: RootModelDictStrAny
}
get_tasks: {
input: GetTasksRequest
output: RootModelDictStrAny
}
get_available_agents: {
input: GetAvailableAgentsRequest
output: RootModelDictStrAny
}
get_task_status: {
input: ExecuteTaskRequest
output: RootModelDictStrAny
}
get_image_stats: {
input: void | undefined
output: RootModelDict
}
get_cached_images: {
input: GetImagesRequest
output: RootModelDict
}
cleanup_old_images: {
input: CleanupImagesRequest
output: RootModelDict
}
clear_memory_cache: {
input: void | undefined
output: RootModelDict
}
get_image_optimization_stats: {
input: void | undefined
output: RootModelDict
}
create_conversation: {
input: CreateConversationRequest
output: RootModelDictStrAny
}
create_conversation_from_activities: {
input: CreateConversationFromActivitiesRequest
output: RootModelDictStrAny
}
send_message: {
input: SendMessageRequest
output: RootModelDictStrAny
}
get_conversations: {
input: GetConversationsRequest
output: RootModelDictStrAny
}
get_messages: {
input: GetMessagesRequest
output: RootModelDictStrAny
}
delete_conversation: {
input: DeleteConversationRequest
output: RootModelDictStrAny
}
get_llm_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_llm_stats_by_model: {
input: GetLLMStatsByModelRequest
output: RootModelDictStrAny
}
record_llm_usage: {
input: RecordLLMUsageRequest
output: RootModelDictStrAny
}
get_usage_summary: {
input: void | undefined
output: RootModelDictStrAny
}
get_daily_llm_usage: {
input: void | undefined
output: RootModelDictStrAny
}
get_model_distribution: {
input: void | undefined
output: RootModelDictStrAny
}
create_model: {
input: CreateModelRequest
output: RootModelDictStrAny
}
update_model: {
input: UpdateModelRequest
output: RootModelDictStrAny
}
delete_model: {
input: DeleteModelRequest
output: RootModelDictStrAny
}
list_models: {
input: void | undefined
output: RootModelDictStrAny
}
get_active_model: {
input: void | undefined
output: RootModelDictStrAny
}
select_model: {
input: SelectModelRequest
output: RootModelDictStrAny
}
test_model: {
input: TestModelRequest
output: RootModelDictStrAny
}
get_recent_events: {
input: GetRecentEventsRequest
output: RootModelDictStrAny
}
get_knowledge_list: {
input: void | undefined
output: RootModelDictStrAny
}
delete_knowledge: {
input: DeleteItemRequest
output: RootModelDictStrAny
}
get_todo_list: {
input: GetTodoListRequest
output: RootModelDictStrAny
}
delete_todo: {
input: DeleteItemRequest
output: RootModelDictStrAny
}
generate_diary: {
input: GenerateDiaryRequest
output: RootModelDictStrAny
}
get_diary_list: {
input: GetDiaryListRequest
output: RootModelDictStrAny
}
delete_diary: {
input: DeleteItemRequest
output: RootModelDictStrAny
}
get_pipeline_stats: {
input: void | undefined
output: RootModelDictStrAny
}
}
/**
 * A simple model representing a person.
 * 
 * @property name - The name of the person.
 */
export interface Person {
name: Name
}
export interface RootModelDictStrAny {
[k: string]: unknown
}
/**
 * Request parameters for getting records.
 * 
 * @property limit - Maximum number of records to return (1-1000).
 * @property eventType - Optional event type filter.
 * @property startTime - Optional start time filter (ISO format).
 * @property endTime - Optional end time filter (ISO format).
 */
export interface GetRecordsRequest {
limit?: Limit
eventType?: Eventtype
startTime?: Starttime
endTime?: Endtime
}
/**
 * Request parameters for getting events.
 * 
 * @property limit - Maximum number of events to return (1-500).
 * @property eventType - Optional event type filter.
 * @property startTime - Optional start time filter (ISO format).
 * @property endTime - Optional end time filter (ISO format).
 */
export interface GetEventsRequest {
limit?: Limit1
eventType?: Eventtype1
startTime?: Starttime1
endTime?: Endtime1
}
/**
 * Request parameters for getting activities.
 * 
 * @property limit - Maximum number of activities to return (1-100).
 */
export interface GetActivitiesRequest {
limit?: Limit2
offset?: Offset
}
/**
 * Request parameters for getting event by ID.
 * 
 * @property eventId - The event ID.
 */
export interface GetEventByIdRequest {
eventId: Eventid
}
/**
 * Request parameters for getting activity by ID.
 * 
 * @property activityId - The activity ID.
 */
export interface GetActivityByIdRequest {
activityId: Activityid
}
/**
 * Request parameters for deleting an activity.
 * 
 * @property activityId - The activity ID to delete.
 */
export interface DeleteActivityRequest {
activityId: Activityid1
}
/**
 * Request parameters for cleaning up old data.
 * 
 * @property days - Number of days to keep (1-365).
 */
export interface CleanupOldDataRequest {
days?: Days
}
/**
 * Request parameters for incremental activity updates.
 * 
 * @property version - The current version number from client (starts at 0).
 * @property limit - Maximum number of new activities to return (1-100).
 */
export interface GetActivitiesIncrementalRequest {
version?: Version
limit?: Limit3
}
/**
 * Request parameters for getting activity count by date.
 * 
 * Returns the total activity count for each date (不分页，获取所有日期的总数).
 */
export interface GetActivityCountByDateRequest {

}
/**
 * Request parameters for updating application settings.
 * 
 * 注意: LLM 配置已迁移到多模型管理系统
 * 参见 CreateModelRequest 和 SelectModelRequest
 * 
 * @property databasePath - Path to the database file (optional).
 * @property screenshotSavePath - Path to save screenshots (optional).
 */
export interface UpdateSettingsRequest {
databasePath?: Databasepath
screenshotSavePath?: Screenshotsavepath
}
export interface RootModelDict {
[k: string]: unknown
}
/**
 * 图像优化配置更新请求
 */
export interface ImageOptimizationConfigRequest {
enabled?: Enabled
strategy?: Strategy
phashThreshold?: Phashthreshold
minInterval?: Mininterval
maxImages?: Maximages
enableContentAnalysis?: Enablecontentanalysis
enableTextDetection?: Enabletextdetection
}
/**
 * Request parameters for updating image compression configuration.
 * 
 * @property compressionLevel - Compression level ('ultra', 'aggressive', 'balanced', 'quality').
 * @property enableRegionCropping - Whether to enable region-based cropping.
 * @property cropThreshold - Crop threshold percentage (0-100).
 */
export interface ImageCompressionConfigRequest {
compressionLevel?: Compressionlevel
enableRegionCropping?: Enableregioncropping
cropThreshold?: Cropthreshold
}
/**
 * Request parameters for creating a new agent task.
 * 
 * @property agent - The agent type to use.
 * @property planDescription - The task description/plan.
 */
export interface CreateTaskRequest {
agent: Agent
planDescription: Plandescription
}
/**
 * Request parameters for executing a task.
 * 
 * @property taskId - The task ID to execute.
 */
export interface ExecuteTaskRequest {
taskId: Taskid
}
/**
 * Request parameters for deleting a task.
 * 
 * @property taskId - The task ID to delete.
 */
export interface DeleteTaskRequest {
taskId: Taskid1
}
/**
 * Request parameters for getting tasks.
 * 
 * @property limit - Maximum number of tasks to return (1-100).
 * @property status - Optional status filter.
 */
export interface GetTasksRequest {
limit?: Limit4
status?: Status
}
/**
 * Request parameters for getting available agents.
 * 
 * No parameters needed.
 */
export interface GetAvailableAgentsRequest {

}
/**
 * 获取图片请求模型
 */
export interface GetImagesRequest {
hashes: Hashes
}
/**
 * 清理图片请求模型
 */
export interface CleanupImagesRequest {
maxAgeHours?: Maxagehours
}
/**
 * 创建对话请求
 */
export interface CreateConversationRequest {
title: Title
relatedActivityIds?: Relatedactivityids
metadata?: Metadata
}
/**
 * 从活动创建对话请求
 */
export interface CreateConversationFromActivitiesRequest {
activityIds: Activityids
}
/**
 * 发送消息请求
 */
export interface SendMessageRequest {
conversationId: Conversationid
content: Content
}
/**
 * 获取对话列表请求
 */
export interface GetConversationsRequest {
limit?: Limit5
offset?: Offset
}
/**
 * 获取消息列表请求
 */
export interface GetMessagesRequest {
conversationId: Conversationid1
limit?: Limit6
offset?: Offset1
}
/**
 * 删除对话请求
 */
export interface DeleteConversationRequest {
conversationId: Conversationid2
}
/**
 * Request parameters for retrieving LLM statistics of a specific model.
 * 
 * @property modelId - The model configuration ID.
 */
export interface GetLLMStatsByModelRequest {
modelId: Modelid
}
/**
 * Request parameters for recording LLM usage statistics.
 * 
 * @property model - The LLM model name used.
 * @property promptTokens - Number of prompt tokens consumed.
 * @property completionTokens - Number of completion tokens consumed.
 * @property totalTokens - Total number of tokens consumed.
 * @property cost - Cost of the request (optional).
 * @property requestType - Type of request (e.g., 'summarization', 'agent', 'chat').
 */
export interface RecordLLMUsageRequest {
model: Model
promptTokens?: Prompttokens
completionTokens?: Completiontokens
totalTokens?: Totaltokens
cost?: Cost
requestType: Requesttype
}
/**
 * Request parameters for creating a new model configuration.
 * 
 * @property name - Display name for the model.
 * @property provider - LLM provider name.
 * @property apiUrl - API endpoint base URL.
 * @property model - Model identifier/name.
 * @property inputTokenPrice - Price per million input tokens.
 * @property outputTokenPrice - Price per million output tokens.
 * @property currency - Currency code (optional, defaults to 'USD').
 * @property apiKey - API authentication key.
 */
export interface CreateModelRequest {
name: Name1
provider: Provider
apiUrl: Apiurl
model: Model1
inputTokenPrice: Inputtokenprice
outputTokenPrice: Outputtokenprice
currency?: Currency
apiKey: Apikey
}
/**
 * Request parameters for updating a model configuration.
 * 
 * @property modelId - The ID of the model to update.
 * @property name - Display name for the model (optional).
 * @property provider - LLM provider name (optional).
 * @property apiUrl - API endpoint base URL (optional).
 * @property model - Model identifier/name (optional).
 * @property inputTokenPrice - Price per million input tokens (optional).
 * @property outputTokenPrice - Price per million output tokens (optional).
 * @property currency - Currency code (optional).
 * @property apiKey - API authentication key (optional, leave empty to keep existing).
 */
export interface UpdateModelRequest {
modelId: Modelid1
name?: Name2
provider?: Provider1
apiUrl?: Apiurl1
model?: Model2
inputTokenPrice?: Inputtokenprice1
outputTokenPrice?: Outputtokenprice1
currency?: Currency1
apiKey?: Apikey1
}
/**
 * Request parameters for deleting a model configuration.
 * 
 * @property modelId - The ID of the model to delete.
 */
export interface DeleteModelRequest {
modelId: Modelid2
}
/**
 * Request parameters for selecting/switching to a model.
 * 
 * @property modelId - The ID of the model to activate.
 */
export interface SelectModelRequest {
modelId: Modelid3
}
/**
 * Request parameters for testing model connectivity.
 * 
 * @property modelId - The ID of the model to test.
 */
export interface TestModelRequest {
modelId: Modelid4
}
/**
 * Request parameters for getting recent events.
 * 
 * @property limit - Maximum number of events to return (1-200).
 */
export interface GetRecentEventsRequest {
limit?: Limit7
}
/**
 * Request parameters for deleting an item (knowledge/todo/diary).
 * 
 * @property id - The item ID to delete.
 */
export interface DeleteItemRequest {
id: Id
}
/**
 * Request parameters for getting todo list.
 * 
 * @property includeCompleted - Whether to include completed todos.
 */
export interface GetTodoListRequest {
includeCompleted?: Includecompleted
}
/**
 * Request parameters for getting diary list.
 * 
 * @property limit - Maximum number of diaries to return (1-100).
 */
export interface GetDiaryListRequest {
limit?: Limit1
}
/**
 * Request parameters for generating a diary.
 * 
 * @property date - The date for the diary (YYYY-MM-DD format).
 */
export interface GenerateDiaryRequest {
date: Date
}
