/* eslint-disable */
/**
 * This file was automatically generated by pytauri-gen-ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source commands API,
 * and run pytauri-gen-ts to regenerate this file.
 */

import { pyInvoke } from "tauri-plugin-pytauri-api";
import type { InvokeOptions } from "@tauri-apps/api/core";

import type { Commands } from "./_apiTypes.d.ts";

/**
 * A simple command that returns a greeting message.
 *
 * @param body - The person to greet.
 */
export async function greeting(
    body: Commands["greeting"]["input"],
    options?: InvokeOptions
): Promise<Commands["greeting"]["output"]> {
    return await pyInvoke("greeting", body, options);
}

/**
 * Get perception module statistics.
 *
 * Returns statistics about the perception module including record counts and status.
 *
 * @returns Statistics data with success flag and timestamp
 */
export async function getPerceptionStats(
    body: Commands["get_perception_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_perception_stats"]["output"]> {
    return await pyInvoke("get_perception_stats", body, options);
}

/**
 * Get perception records with optional filters.
 *
 * @param body - Request parameters including limit and filters.
 * @returns Records data with success flag and timestamp
 */
export async function getRecords(
    body: Commands["get_records"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_records"]["output"]> {
    return await pyInvoke("get_records", body, options);
}

/**
 * Start the perception module.
 *
 * Starts monitoring keyboard, mouse, and screenshots.
 *
 * @returns Success response with message and timestamp
 */
export async function startPerception(
    body: Commands["start_perception"]["input"],
    options?: InvokeOptions
): Promise<Commands["start_perception"]["output"]> {
    return await pyInvoke("start_perception", body, options);
}

/**
 * Stop the perception module.
 *
 * Stops monitoring keyboard, mouse, and screenshots.
 *
 * @returns Success response with message and timestamp
 */
export async function stopPerception(
    body: Commands["stop_perception"]["input"],
    options?: InvokeOptions
): Promise<Commands["stop_perception"]["output"]> {
    return await pyInvoke("stop_perception", body, options);
}

/**
 * Clear all perception records.
 *
 * Removes all stored records and clears the buffer.
 *
 * @returns Success response with message and timestamp
 */
export async function clearRecords(
    body: Commands["clear_records"]["input"],
    options?: InvokeOptions
): Promise<Commands["clear_records"]["output"]> {
    return await pyInvoke("clear_records", body, options);
}

/**
 * Get buffered events.
 *
 * Returns events currently in the buffer waiting to be processed.
 *
 * @returns Buffered events data with success flag and timestamp
 */
export async function getBufferedEvents(
    body: Commands["get_buffered_events"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_buffered_events"]["output"]> {
    return await pyInvoke("get_buffered_events", body, options);
}

/**
 * Get processing module statistics.
 *
 * Returns statistics about event and activity processing.
 *
 * @returns Statistics data with success flag and timestamp
 */
export async function getProcessingStats(
    body: Commands["get_processing_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_processing_stats"]["output"]> {
    return await pyInvoke("get_processing_stats", body, options);
}

/**
 * Get processed events with optional filters.
 *
 * @param body - Request parameters including limit and filters.
 * @returns Events data with success flag and timestamp
 */
export async function getEvents(
    body: Commands["get_events"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_events"]["output"]> {
    return await pyInvoke("get_events", body, options);
}

/**
 * Get processed activities.
 *
 * @param body - Request parameters including limit.
 * @returns Activities data with success flag and timestamp
 */
export async function getActivities(
    body: Commands["get_activities"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_activities"]["output"]> {
    return await pyInvoke("get_activities", body, options);
}

/**
 * Get event details by ID.
 *
 * @param body - Request parameters including event ID.
 * @returns Event details with success flag and timestamp
 */
export async function getEventById(
    body: Commands["get_event_by_id"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_event_by_id"]["output"]> {
    return await pyInvoke("get_event_by_id", body, options);
}

/**
 * Get activity details by ID.
 *
 * @param body - Request parameters including activity ID.
 * @returns Activity details with success flag and timestamp
 */
export async function getActivityById(
    body: Commands["get_activity_by_id"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_activity_by_id"]["output"]> {
    return await pyInvoke("get_activity_by_id", body, options);
}

/**
 * Delete activity by ID.
 *
 * Removes the activity from persistence and emits deletion event to frontend.
 *
 * @param body - Request parameters including activity ID.
 * @returns Deletion result with success flag and timestamp
 */
export async function deleteActivity(
    body: Commands["delete_activity"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_activity"]["output"]> {
    return await pyInvoke("delete_activity", body, options);
}

/**
 * Start the processing pipeline.
 *
 * Begins processing raw records into events and activities.
 *
 * @returns Success response with message and timestamp
 */
export async function startProcessing(
    body: Commands["start_processing"]["input"],
    options?: InvokeOptions
): Promise<Commands["start_processing"]["output"]> {
    return await pyInvoke("start_processing", body, options);
}

/**
 * Stop the processing pipeline.
 *
 * Stops processing raw records.
 *
 * @returns Success response with message and timestamp
 */
export async function stopProcessing(
    body: Commands["stop_processing"]["input"],
    options?: InvokeOptions
): Promise<Commands["stop_processing"]["output"]> {
    return await pyInvoke("stop_processing", body, options);
}

/**
 * Force finalize the current activity.
 *
 * Forces the completion of the current activity being processed.
 *
 * @returns Success response with message and timestamp
 */
export async function finalizeCurrentActivity(
    body: Commands["finalize_current_activity"]["input"],
    options?: InvokeOptions
): Promise<Commands["finalize_current_activity"]["output"]> {
    return await pyInvoke("finalize_current_activity", body, options);
}

/**
 * Clean up old data.
 *
 * @param body - Request parameters including number of days to keep.
 * @returns Cleanup result with success flag and timestamp
 */
export async function cleanupOldData(
    body: Commands["cleanup_old_data"]["input"],
    options?: InvokeOptions
): Promise<Commands["cleanup_old_data"]["output"]> {
    return await pyInvoke("cleanup_old_data", body, options);
}

/**
 * Get persistence statistics.
 *
 * Returns statistics about data persistence including database size and record counts.
 *
 * @returns Statistics data with success flag and timestamp
 */
export async function getPersistenceStats(
    body: Commands["get_persistence_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_persistence_stats"]["output"]> {
    return await pyInvoke("get_persistence_stats", body, options);
}

/**
 * Get incremental activity updates based on version negotiation.
 *
 * This handler implements version-based incremental updates. The client provides
 * its current version number, and the server returns only activities created or
 * updated after that version.
 *
 * @param body - Request parameters including client version and limit.
 * @returns New activities data with success flag, max version, and timestamp
 */
export async function getActivitiesIncremental(
    body: Commands["get_activities_incremental"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_activities_incremental"]["output"]> {
    return await pyInvoke("get_activities_incremental", body, options);
}

/**
 * Get activity count for each date (total count, not paginated).
 *
 * Returns the total number of activities for each date in the database.
 *
 * @param body - Request parameters (empty).
 * @returns Activity count statistics by date
 */
export async function getActivityCountByDate(
    body: Commands["get_activity_count_by_date"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_activity_count_by_date"]["output"]> {
    return await pyInvoke("get_activity_count_by_date", body, options);
}

/**
 * 启动整个后端系统（perception + processing）
 *
 * @returns Success response with message and timestamp
 */
export async function startSystem(
    body: Commands["start_system"]["input"],
    options?: InvokeOptions
): Promise<Commands["start_system"]["output"]> {
    return await pyInvoke("start_system", body, options);
}

/**
 * 停止整个后端系统
 *
 * @returns Success response with message and timestamp
 */
export async function stopSystem(
    body: Commands["stop_system"]["input"],
    options?: InvokeOptions
): Promise<Commands["stop_system"]["output"]> {
    return await pyInvoke("stop_system", body, options);
}

/**
 * 获取系统整体状态
 *
 * @returns System statistics with perception and processing info
 */
export async function getSystemStats(
    body: Commands["get_system_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_system_stats"]["output"]> {
    return await pyInvoke("get_system_stats", body, options);
}

/**
 * 获取后端正在使用的数据库绝对路径
 */
export async function getDatabasePath(
    body: Commands["get_database_path"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_database_path"]["output"]> {
    return await pyInvoke("get_database_path", body, options);
}

/**
 * 获取所有应用配置
 *
 * 注意: LLM 配置已迁移到多模型管理系统
 * 参见 models_management.py 中的 get_active_model()
 *
 * @returns 应用配置信息
 */
export async function getSettingsInfo(
    body: Commands["get_settings_info"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_settings_info"]["output"]> {
    return await pyInvoke("get_settings_info", body, options);
}

/**
 * 更新应用配置
 *
 * 注意: LLM 配置已迁移到多模型管理系统
 * 参见 models_management.py 中的 create_model() 和 select_model()
 *
 * @param body 包含要更新的配置项
 * @returns 更新结果
 */
export async function updateSettings(
    body: Commands["update_settings"]["input"],
    options?: InvokeOptions
): Promise<Commands["update_settings"]["output"]> {
    return await pyInvoke("update_settings", body, options);
}

/**
 * 获取图像优化配置
 *
 * Returns:
 *     当前的图像优化配置
 */
export async function getImageOptimizationConfig(
    body: Commands["get_image_optimization_config"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_image_optimization_config"]["output"]> {
    return await pyInvoke("get_image_optimization_config", body, options);
}

/**
 * 更新图像优化配置
 *
 * Args:
 *     body: 包含新配置的请求体
 *
 * Returns:
 *     更新结果
 */
export async function updateImageOptimizationConfig(
    body: Commands["update_image_optimization_config"]["input"],
    options?: InvokeOptions
): Promise<Commands["update_image_optimization_config"]["output"]> {
    return await pyInvoke("update_image_optimization_config", body, options);
}

/**
 * 获取图像压缩配置
 *
 * @returns 图像压缩配置信息
 */
export async function getImageCompressionConfig(
    body: Commands["get_image_compression_config"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_image_compression_config"]["output"]> {
    return await pyInvoke("get_image_compression_config", body, options);
}

/**
 * 更新图像压缩配置
 *
 * @param body 包含要更新的图像压缩配置项
 * @returns 更新结果
 */
export async function updateImageCompressionConfig(
    body: Commands["update_image_compression_config"]["input"],
    options?: InvokeOptions
): Promise<Commands["update_image_compression_config"]["output"]> {
    return await pyInvoke("update_image_compression_config", body, options);
}

/**
 * 获取图像压缩统计信息
 *
 * @returns 图像压缩统计数据
 */
export async function getImageCompressionStats(
    body: Commands["get_image_compression_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_image_compression_stats"]["output"]> {
    return await pyInvoke("get_image_compression_stats", body, options);
}

/**
 * 重置图像压缩统计信息
 *
 * @returns 重置结果
 */
export async function resetImageCompressionStats(
    body: Commands["reset_image_compression_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["reset_image_compression_stats"]["output"]> {
    return await pyInvoke("reset_image_compression_stats", body, options);
}

/**
 * 创建新的Agent任务
 */
export async function createTask(
    body: Commands["create_task"]["input"],
    options?: InvokeOptions
): Promise<Commands["create_task"]["output"]> {
    return await pyInvoke("create_task", body, options);
}

/**
 * 执行Agent任务
 */
export async function executeTask(
    body: Commands["execute_task"]["input"],
    options?: InvokeOptions
): Promise<Commands["execute_task"]["output"]> {
    return await pyInvoke("execute_task", body, options);
}

/**
 * 删除Agent任务
 */
export async function deleteTask(
    body: Commands["delete_task"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_task"]["output"]> {
    return await pyInvoke("delete_task", body, options);
}

/**
 * 获取Agent任务列表
 */
export async function getTasks(
    body: Commands["get_tasks"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_tasks"]["output"]> {
    return await pyInvoke("get_tasks", body, options);
}

/**
 * 获取可用的Agent列表
 */
export async function getAvailableAgents(
    body: Commands["get_available_agents"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_available_agents"]["output"]> {
    return await pyInvoke("get_available_agents", body, options);
}

/**
 * 获取任务状态
 */
export async function getTaskStatus(
    body: Commands["get_task_status"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_task_status"]["output"]> {
    return await pyInvoke("get_task_status", body, options);
}

/**
 * 获取图片缓存统计信息
 *
 * Returns:
 *     图片缓存和磁盘使用统计
 */
export async function getImageStats(
    body: Commands["get_image_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_image_stats"]["output"]> {
    return await pyInvoke("get_image_stats", body, options);
}

/**
 * 批量获取内存中的图片（base64格式）
 *
 * Args:
 *     body: 包含图片 hash 列表的请求
 *
 * Returns:
 *     包含 base64 数据的字典
 */
export async function getCachedImages(
    body: Commands["get_cached_images"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_cached_images"]["output"]> {
    return await pyInvoke("get_cached_images", body, options);
}

/**
 * 清理旧的图片文件
 *
 * Args:
 *     body: 包含最大保留时间的请求
 *
 * Returns:
 *     清理结果统计
 */
export async function cleanupOldImages(
    body: Commands["cleanup_old_images"]["input"],
    options?: InvokeOptions
): Promise<Commands["cleanup_old_images"]["output"]> {
    return await pyInvoke("cleanup_old_images", body, options);
}

/**
 * 清空内存缓存
 *
 * Returns:
 *     清理结果
 */
export async function clearMemoryCache(
    body: Commands["clear_memory_cache"]["input"],
    options?: InvokeOptions
): Promise<Commands["clear_memory_cache"]["output"]> {
    return await pyInvoke("clear_memory_cache", body, options);
}

/**
 * 获取图像优化统计信息
 *
 * Returns:
 *     包含采样统计、跳过原因分布等信息
 */
export async function getImageOptimizationStats(
    body: Commands["get_image_optimization_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_image_optimization_stats"]["output"]> {
    return await pyInvoke("get_image_optimization_stats", body, options);
}

/**
 * 创建新对话
 *
 * Args:
 *     body: 包含标题、关联活动等信息
 *
 * Returns:
 *     创建的对话信息
 */
export async function createConversation(
    body: Commands["create_conversation"]["input"],
    options?: InvokeOptions
): Promise<Commands["create_conversation"]["output"]> {
    return await pyInvoke("create_conversation", body, options);
}

/**
 * 从活动创建对话，自动生成上下文
 *
 * Args:
 *     body: 包含活动 ID 列表
 *
 * Returns:
 *     创建的对话信息和上下文
 */
export async function createConversationFromActivities(
    body: Commands["create_conversation_from_activities"]["input"],
    options?: InvokeOptions
): Promise<Commands["create_conversation_from_activities"]["output"]> {
    return await pyInvoke("create_conversation_from_activities", body, options);
}

/**
 * 发送消息（流式输出）
 *
 * 此接口会启动流式输出，通过 Tauri Events 实时发送消息块。
 * 前端应监听 'chat-message-chunk' 事件来接收流式内容。
 *
 * Args:
 *     body: 包含对话 ID 和消息内容
 *
 * Returns:
 *     操作状态
 */
export async function sendMessage(
    body: Commands["send_message"]["input"],
    options?: InvokeOptions
): Promise<Commands["send_message"]["output"]> {
    return await pyInvoke("send_message", body, options);
}

/**
 * 获取对话列表
 *
 * Args:
 *     body: 包含分页参数
 *
 * Returns:
 *     对话列表
 */
export async function getConversations(
    body: Commands["get_conversations"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_conversations"]["output"]> {
    return await pyInvoke("get_conversations", body, options);
}

/**
 * 获取对话的消息列表
 *
 * Args:
 *     body: 包含对话 ID 和分页参数
 *
 * Returns:
 *     消息列表
 */
export async function getMessages(
    body: Commands["get_messages"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_messages"]["output"]> {
    return await pyInvoke("get_messages", body, options);
}

/**
 * 删除对话（级联删除所有消息）
 *
 * Args:
 *     body: 包含对话 ID
 *
 * Returns:
 *     操作状态
 */
export async function deleteConversation(
    body: Commands["delete_conversation"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_conversation"]["output"]> {
    return await pyInvoke("delete_conversation", body, options);
}

/**
 * 获取LLM使用统计信息
 *
 * @returns LLM token消耗统计和调用次数
 */
export async function getLlmStats(
    body: Commands["get_llm_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_llm_stats"]["output"]> {
    return await pyInvoke("get_llm_stats", body, options);
}

/**
 * 按模型获取LLM使用统计信息
 */
export async function getLlmStatsByModel(
    body: Commands["get_llm_stats_by_model"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_llm_stats_by_model"]["output"]> {
    return await pyInvoke("get_llm_stats_by_model", body, options);
}

/**
 * 记录LLM使用统计
 *
 * @param body LLM使用信息
 * @returns 记录结果
 */
export async function recordLlmUsage(
    body: Commands["record_llm_usage"]["input"],
    options?: InvokeOptions
): Promise<Commands["record_llm_usage"]["output"]> {
    return await pyInvoke("record_llm_usage", body, options);
}

/**
 * 获取整体使用量摘要统计
 *
 * @returns 包括活动、任务、LLM使用的总体摘要
 */
export async function getUsageSummary(
    body: Commands["get_usage_summary"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_usage_summary"]["output"]> {
    return await pyInvoke("get_usage_summary", body, options);
}

/**
 * 获取每日LLM使用情况
 *
 * @returns 每日LLM使用数据列表
 */
export async function getDailyLlmUsage(
    body: Commands["get_daily_llm_usage"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_daily_llm_usage"]["output"]> {
    return await pyInvoke("get_daily_llm_usage", body, options);
}

/**
 * 获取模型使用分布统计
 *
 * @returns 模型使用分布数据
 */
export async function getModelDistribution(
    body: Commands["get_model_distribution"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_model_distribution"]["output"]> {
    return await pyInvoke("get_model_distribution", body, options);
}

/**
 * 创建新的模型配置
 *
 * @param body 模型配置信息（包含API密钥）
 * @returns 创建的模型信息
 */
export async function createModel(
    body: Commands["create_model"]["input"],
    options?: InvokeOptions
): Promise<Commands["create_model"]["output"]> {
    return await pyInvoke("create_model", body, options);
}

/**
 * 更新模型配置
 *
 * @param body 要更新的模型信息（只更新提供的字段）
 * @returns 更新后的模型信息
 */
export async function updateModel(
    body: Commands["update_model"]["input"],
    options?: InvokeOptions
): Promise<Commands["update_model"]["output"]> {
    return await pyInvoke("update_model", body, options);
}

/**
 * 删除模型配置
 *
 * @param body 要删除的模型 ID
 * @returns 删除结果
 */
export async function deleteModel(
    body: Commands["delete_model"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_model"]["output"]> {
    return await pyInvoke("delete_model", body, options);
}

/**
 * 获取所有模型配置列表
 *
 * @returns 模型列表（不包含API密钥）
 */
export async function listModels(
    body: Commands["list_models"]["input"],
    options?: InvokeOptions
): Promise<Commands["list_models"]["output"]> {
    return await pyInvoke("list_models", body, options);
}

/**
 * 获取当前激活的模型信息
 *
 * @returns 激活模型的详细信息（不包含API密钥）
 */
export async function getActiveModel(
    body: Commands["get_active_model"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_active_model"]["output"]> {
    return await pyInvoke("get_active_model", body, options);
}

/**
 * 选择/激活指定的模型
 *
 * @param body 包含要激活的模型 ID
 * @returns 激活结果和新的模型信息
 */
export async function selectModel(
    body: Commands["select_model"]["input"],
    options?: InvokeOptions
): Promise<Commands["select_model"]["output"]> {
    return await pyInvoke("select_model", body, options);
}

/**
 * 测试指定模型的 API 连接是否可用
 */
export async function testModel(
    body: Commands["test_model"]["input"],
    options?: InvokeOptions
): Promise<Commands["test_model"]["output"]> {
    return await pyInvoke("test_model", body, options);
}

/**
 * 获取最近的events
 *
 * @param body - 请求参数，包含limit和offset
 * @returns events列表和元数据
 */
export async function getRecentEvents(
    body: Commands["get_recent_events"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_recent_events"]["output"]> {
    return await pyInvoke("get_recent_events", body, options);
}

/**
 * 获取knowledge列表
 *
 * @returns knowledge列表（优先返回combined）
 */
export async function getKnowledgeList(
    body: Commands["get_knowledge_list"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_knowledge_list"]["output"]> {
    return await pyInvoke("get_knowledge_list", body, options);
}

/**
 * 删除knowledge（软删除）
 *
 * @param body - 包含要删除的knowledge ID
 * @returns 删除结果
 */
export async function deleteKnowledge(
    body: Commands["delete_knowledge"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_knowledge"]["output"]> {
    return await pyInvoke("delete_knowledge", body, options);
}

/**
 * 获取todo列表
 *
 * @param body - 请求参数，包含include_completed
 * @returns todo列表（优先返回combined）
 */
export async function getTodoList(
    body: Commands["get_todo_list"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_todo_list"]["output"]> {
    return await pyInvoke("get_todo_list", body, options);
}

/**
 * 删除todo（软删除）
 *
 * @param body - 包含要删除的todo ID
 * @returns 删除结果
 */
export async function deleteTodo(
    body: Commands["delete_todo"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_todo"]["output"]> {
    return await pyInvoke("delete_todo", body, options);
}

/**
 * 生成日记
 *
 * @param body - 包含日期（YYYY-MM-DD格式）
 * @returns 生成的日记内容
 */
export async function generateDiary(
    body: Commands["generate_diary"]["input"],
    options?: InvokeOptions
): Promise<Commands["generate_diary"]["output"]> {
    return await pyInvoke("generate_diary", body, options);
}

/**
 * 获取日记列表
 */
export async function getDiaryList(
    body: Commands["get_diary_list"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_diary_list"]["output"]> {
    return await pyInvoke("get_diary_list", body, options);
}

/**
 * 删除日记
 *
 * @param body - 包含要删除的diary ID
 * @returns 删除结果
 */
export async function deleteDiary(
    body: Commands["delete_diary"]["input"],
    options?: InvokeOptions
): Promise<Commands["delete_diary"]["output"]> {
    return await pyInvoke("delete_diary", body, options);
}

/**
 * 获取pipeline统计信息
 *
 * @returns pipeline运行状态和统计数据
 */
export async function getPipelineStats(
    body: Commands["get_pipeline_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_pipeline_stats"]["output"]> {
    return await pyInvoke("get_pipeline_stats", body, options);
}

/**
 * 检查所有必需的系统权限
 *
 * Returns:
 *     权限检查结果，包含每个权限的状态
 */
export async function checkPermissions(
    body: Commands["check_permissions"]["input"],
    options?: InvokeOptions
): Promise<Commands["check_permissions"]["output"]> {
    return await pyInvoke("check_permissions", body, options);
}

/**
 * 打开系统设置对应的权限页面
 *
 * Args:
 *     body: 包含要打开的权限类型
 *
 * Returns:
 *     操作结果
 */
export async function openSystemSettings(
    body: Commands["open_system_settings"]["input"],
    options?: InvokeOptions
): Promise<Commands["open_system_settings"]["output"]> {
    return await pyInvoke("open_system_settings", body, options);
}

/**
 * 请求辅助功能权限（仅 macOS）
 *
 * 这将触发系统权限对话框
 *
 * Returns:
 *     请求结果
 */
export async function requestAccessibilityPermission(
    body: Commands["request_accessibility_permission"]["input"],
    options?: InvokeOptions
): Promise<Commands["request_accessibility_permission"]["output"]> {
    return await pyInvoke("request_accessibility_permission", body, options);
}

/**
 * 重启应用程序
 *
 * Args:
 *     body: 包含延迟时间的请求
 *
 * Returns:
 *     操作结果
 */
export async function restartApp(
    body: Commands["restart_app"]["input"],
    options?: InvokeOptions
): Promise<Commands["restart_app"]["output"]> {
    return await pyInvoke("restart_app", body, options);
}
